# Title

In [1]:
# import all necessary libraries
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np

### Read data

In [2]:
data_2018 = pd.read_csv('2018_Data.csv', encoding='latin-1')
data_2018

,Driver Name,Salary in USD,Team,Driver Status,Age,Number of World Championships,Number of Pole Positions,Number of Race Wins,Number of Podiums,Number of DNF,Number of DSQ,Number of DNS,WD,Average Grid Position,Average Finish Position,Lead Lap Finish,Points,Number of Fastest Laps,Rookie Status,Pay Driver?
0,Sebastian Vettel,"$60,000,000.00",Ferrari,0,31,4,5,5,12,1,0,0,0,2.9,3.9,20,320,3,0,0
1,Lewis Hamiton,"$50,000,000.00",Mercedes,0,33,4,11,11,17,1,0,0,0,2.7,2.6,20,408,3,0,0
2,Kimi Räikkönen,"$40,000,000.00",Ferrari,1,38,1,1,1,12,4,0,0,0,3.8,6.0,17,251,1,0,0
3,Fernando Alonso,"$30,000,000.00",McLaren F1 Team,0,37,2,0,0,0,8,0,0,0,13.2,12.8,5,50,0,0,0
4,Valtteri Bottas,"$12,000,000.00",Mercedes,1,29,0,2,0,8,2,0,0,0,4.0,5.1,18,247,7,0,0
5,Max Verstappen,"$10,000,000.00",Red Bull Racing,0,20,0,2,2,11,4,0,0,0,7.1,6.1,17,249,2,0,0
6,Stoffel Vandoorne,"$7,000,000.00",McLaren F1 Team,1,26,0,0,0,0,3,0,0,0,15.8,12.9,5,12,0,0,0
7,Daniel Ricciardo,"$6,000,000.00",Red Bull Racing,1,29,0,1,2,2,8,0,0,0,8.2,9.3,13,170,4,0,0
8,Nico Hülkenberg,"$5,500,000.00",Renault F1 Team,0,31,0,0,0,0,7,0,0,0,11.2,11.9,8,69,0,0,0
9,Sergio Pérez,"$5,000,000.00",Force India,0,28,0,0,0,1,2,0,0,0,11.1,10.6,11,62,0,0,1
10,Romain Grosjean,"$4,450,000.00",Haas,0,32,0,0,0,0,6,1,0,0,10.1,12.7,6,37,0,0,0
11,Esteban Ocon,"$3,000,000.00",Force India,1,21,0,0,0,0,6,1,0,0,10.1,11.6,9,49,0,0,0
12,Kevin Magnussen,"$2,500,000.00",Haas,0,25,0,0,0,0,3,1,0,0,10.3,11.2,3,56,1,0,0
13,Lance Stroll,"$1,800,000.00",Williams,0,19,0,0,0,0,3,0,0,0,16.5,14.2,4,6,0,0,1
14,Sergey Sirotkin,"$1,000,000.00",Williams,0,23,0,0,0,0,3,0,0,0,16.1,15.5,2,1,0,1,1
15,Carlos Sainz Jr,"$750,000.00",Renault,1,23,0,0,0,0,2,0,0,0,10.2,10.3,9,53,0,0,0
16,Marcus Ericsson,"$500,000.00",Sauber,0,27,0,0,0,0,4,0,0,0,15.1,13.2,4,9,0,0,1
17,Pierre Gasly,"$400,000.00",Toro Rosso,0,22,0,0,0,0,5,0,0,0,13.8,12.9,7,29,0,0,0
18,Brendon Hartley,"$350,000.00",Toro Rosso,1,28,0,0,0,0,7,0,0,0,15.5,15.0,2,4,0,0,1
19,Charles Leclerc,"$150,000.00",Sauber,1,20,0,0,0,0,6,0,0,0,12.3,12.5,7,39,0,1,0

### Insert Data Dictionary

### Check Missing Data

In [3]:
null_values_col = data_2018.isnull().sum() 
null_values_col = null_values_col[null_values_col != 0].sort_values(ascending = False).reset_index() 
null_values_col.columns = ["variable", "number of missing"] 
null_values_col.head()

Empty DataFrame
Columns: [variable, number of missing]
Index: []

There are no missing values.

### Descriptive Statistics

In [4]:
data_2018.describe()

,Driver Status,Age,Number of World Championships,Number of Pole Positions,Number of Race Wins,Number of Podiums,Number of DNF,Number of DSQ,Number of DNS,WD,Average Grid Position,Average Finish Position,Lead Lap Finish,Points,Number of Fastest Laps,Rookie Status,Pay Driver?
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.0,20.0,20.000000,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,0.400000,27.100000,0.550000,1.100000,1.050000,3.150000,4.250000,0.150000,0.0,0.0,10.500000,10.51500,9.350000,106.050000,1.050000,0.100000,0.250000
std,0.502625,5.543132,1.276302,2.633789,2.645254,5.470254,2.244877,0.366348,0.0,0.0,4.512672,3.78199,6.080815,121.893601,1.877148,0.307794,0.444262
min,0.000000,19.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,2.700000,2.60000,2.000000,1.000000,0.000000,0.000000,0.000000
25%,0.000000,22.750000,0.000000,0.000000,0.000000,0.000000,2.750000,0.000000,0.0,0.0,7.925000,8.50000,4.750000,24.750000,0.000000,0.000000,0.000000
50%,0.000000,27.500000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.0,0.0,10.700000,11.75000,7.500000,51.500000,0.000000,0.000000,0.000000
75%,1.000000,31.000000,0.000000,1.000000,0.250000,3.500000,6.000000,0.000000,0.0,0.0,14.125000,12.90000,14.000000,189.250000,1.250000,0.000000,0.250000
max,1.000000,38.000000,4.000000,11.000000,11.000000,17.000000,8.000000,1.000000,0.0,0.0,16.500000,15.50000,20.000000,408.000000,7.000000,1.000000,1.000000

In [5]:
data_2018['Salary in USD'].head()

0    $60,000,000.00
1    $50,000,000.00
2    $40,000,000.00
3    $30,000,000.00
4    $12,000,000.00
Name: Salary in USD, dtype: object